### PR TITLE
Feature/schedules

### PR DESCRIPTION
**Pull request by santostiago**
Changed the stores endpoint in order to accomplish 2 things:
1. To be able to sort by a field that doesn't exist in the model (jsonapi-resources doesn't allow for it)
2. To be able to have the current day in the model without having the N+1 problem (this would only work in jsonapi-resources if I didn't flatten the relationship, and we'd always have to have the `include=current-day` in the request).

That way, for that endpoint I'm using the fast jsonapi.

### CODE REVIEW

**Comment by simaob** [comment]
can you share the example endpoints?

**Comment by simaob** [comment]
I rebased with develop, btw.

**Comment by santostiago** [comment]
The requests didn't change.
I just added a jsonapi filter:  `filter[store-type]=supermarket`.

**Comment by santostiago** [comment]
I'm going to merge this cause I need to for the next tasks.

**Pull request merged**
